services:
  emsi-bank-discovery-service:
    build: ./discovery-service
    container_name: emsi-bank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
  emsi-bank-config-service:
    build: ./discovery-service
    container_name: emsi-bank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://emsi-bank-discovery-service:8761/eureka
    depends_on:
      emsi-bank-discovery-service:
        condition: service_healthy